import { useMemo } from 'react';

type UseComBrowserPanelPropsArgs = any;

export default function useComBrowserPanelProps(args: UseComBrowserPanelPropsArgs) {
  const {
    hasEditPermission,
    setShowPathModal,
    breadcrumbs,
    handleCrumbClick,
    searchQuery,
    setSearchQuery,
    searchScope,
    setSearchScope,
    handleSearchSubmit,
    searchLoading,
    clearSearch,
    handleResetNavigation,
    favoritesFolders,
    favoritesFiles,
    favoritesLoading,
    favoritesError,
    handleOpenFolder,
    openFileFromUrl,
    handleOpenSearchResult,
    searchResults,
    searchError,
    getSearchResultName,
    browseError,
    browseLoading,
    entries,
    isFolder,
    handleOpenFile,
  } = args;

  return useMemo(
    () => ({
      hasEditPermission,
      setShowPathModal,
      breadcrumbs,
      handleCrumbClick,
      searchQuery,
      setSearchQuery,
      searchScope,
      setSearchScope,
      handleSearchSubmit,
      searchLoading,
      handleClearSearch: clearSearch,
      handleResetNavigation,
      favoritesFolders,
      favoritesFiles,
      favoritesLoading,
      favoritesError,
      handleOpenFolder,
      openFileFromUrl,
      handleOpenSearchResult,
      searchResults,
      searchError,
      getSearchResultName,
      browseError,
      browseLoading,
      entries,
      isFolder,
      handleOpenFile,
    }),
    [
      hasEditPermission,
      setShowPathModal,
      breadcrumbs,
      handleCrumbClick,
      searchQuery,
      setSearchQuery,
      searchScope,
      setSearchScope,
      handleSearchSubmit,
      searchLoading,
      clearSearch,
      handleResetNavigation,
      favoritesFolders,
      favoritesFiles,
      favoritesLoading,
      favoritesError,
      handleOpenFolder,
      openFileFromUrl,
      handleOpenSearchResult,
      searchResults,
      searchError,
      getSearchResultName,
      browseError,
      browseLoading,
      entries,
      isFolder,
      handleOpenFile,
    ],
  );
}
