import { useMemo } from 'react';

type UseFcomReviewCommitModalPropsArgs = any;

export default function useFcomReviewCommitModalProps(args: UseFcomReviewCommitModalPropsArgs) {
  const {
    open,
    reviewStep,
    stagedDiff,
    expandedOriginals,
    setExpandedOriginals,
    stagedSectionOpen,
    setStagedSectionOpen,
    getFieldChangeLabel,
    getBaseObjectValue,
    renderInlineDiff,
    getProcessorType,
    getProcessorSummaryLines,
    saveLoading,
    hasEditPermission,
    onClose,
    onDiscardChanges,
    setReviewStep,
    commitMessage,
    setCommitMessage,
    onCommit,
  } = args;

  return useMemo(
    () => ({
      open,
      reviewStep,
      stagedDiff,
      expandedOriginals,
      setExpandedOriginals,
      stagedSectionOpen,
      setStagedSectionOpen,
      getFieldChangeLabel,
      getBaseObjectValue,
      renderInlineDiff,
      getProcessorType,
      getProcessorSummaryLines,
      saveLoading,
      hasEditPermission,
      onClose,
      onDiscardChanges,
      setReviewStep,
      commitMessage,
      setCommitMessage,
      onCommit,
    }),
    [
      open,
      reviewStep,
      stagedDiff,
      expandedOriginals,
      setExpandedOriginals,
      stagedSectionOpen,
      setStagedSectionOpen,
      getFieldChangeLabel,
      getBaseObjectValue,
      renderInlineDiff,
      getProcessorType,
      getProcessorSummaryLines,
      saveLoading,
      hasEditPermission,
      onClose,
      onDiscardChanges,
      setReviewStep,
      commitMessage,
      setCommitMessage,
      onCommit,
    ],
  );
}