import { useMemo } from 'react';

type UseMicroserviceModalHostArgsArgs = any;

export default function useMicroserviceModalHostArgs(args: UseMicroserviceModalHostArgsArgs) {
  const {
    redeployModalOpen,
    redeployReady,
    showMicroserviceWarning,
    missingMicroservices,
    unhealthyMicroservices,
    microserviceStatusError,
    microserviceIsStale,
    microserviceLastRefreshed,
    redeployError,
    microserviceStatusLoading,
    requiredMicroservices,
    microserviceActionLabel,
    redeployLoading,
    hasEditPermission,
    formatTime,
    getServiceTone,
    getServiceStatusText,
    handleDeployMicroservice,
    handleRedeployMicroservice,
    setRedeployModalOpen,
    setRedeployError,
    setMicroserviceActionLabel,
    refreshMicroserviceStatus,
    handleRedeployFcomProcessor,
  } = args;

  return useMemo(
    () => ({
      redeployModalOpen,
      redeployReady,
      showMicroserviceWarning,
      missingMicroservices,
      unhealthyMicroservices,
      microserviceStatusError,
      microserviceIsStale,
      microserviceLastRefreshed,
      redeployError,
      microserviceStatusLoading,
      requiredMicroservices,
      microserviceActionLabel,
      redeployLoading,
      hasEditPermission,
      formatTime,
      getServiceTone,
      getServiceStatusText,
      handleDeployMicroservice,
      handleRedeployMicroservice,
      setRedeployModalOpen,
      setRedeployError,
      setMicroserviceActionLabel,
      refreshMicroserviceStatus,
      handleRedeployFcomProcessor,
    }),
    [
      redeployModalOpen,
      redeployReady,
      showMicroserviceWarning,
      missingMicroservices,
      unhealthyMicroservices,
      microserviceStatusError,
      microserviceIsStale,
      microserviceLastRefreshed,
      redeployError,
      microserviceStatusLoading,
      requiredMicroservices,
      microserviceActionLabel,
      redeployLoading,
      hasEditPermission,
      formatTime,
      getServiceTone,
      getServiceStatusText,
      handleDeployMicroservice,
      handleRedeployMicroservice,
      setRedeployModalOpen,
      setRedeployError,
      setMicroserviceActionLabel,
      refreshMicroserviceStatus,
      handleRedeployFcomProcessor,
    ],
  );
}