import { useMemo } from 'react';

type UsePcomAdvancedSettingsModalPropsArgs = any;

export default function usePcomAdvancedSettingsModalProps(
  args: UsePcomAdvancedSettingsModalPropsArgs,
) {
  const {
    open,
    pcomAdvancedTargetMode,
    setPcomAdvancedTargetMode,
    pcomAdvancedDeviceIp,
    setPcomAdvancedDeviceIp,
    pcomDevicesLoading,
    pcomDeviceOptions,
    pcomAdvancedManualIp,
    setPcomAdvancedManualIp,
    pcomAdvancedSnmpVersion,
    setPcomAdvancedSnmpVersion,
    pcomAdvancedCommunity,
    setPcomAdvancedCommunity,
    pcomAdvancedOidEnabled,
    setPcomAdvancedOidEnabled,
    pcomAdvancedOidValue,
    setPcomAdvancedOidValue,
    pcomAdvancedSecurityLevel,
    setPcomAdvancedSecurityLevel,
    pcomAdvancedUsername,
    setPcomAdvancedUsername,
    pcomAdvancedAuthProtocol,
    setPcomAdvancedAuthProtocol,
    pcomAdvancedAuthPassword,
    setPcomAdvancedAuthPassword,
    pcomAdvancedPrivProtocol,
    setPcomAdvancedPrivProtocol,
    pcomAdvancedPrivPassword,
    setPcomAdvancedPrivPassword,
    pcomAdvancedEngineId,
    setPcomAdvancedEngineId,
    onClose,
    onApply,
  } = args;

  return useMemo(
    () => ({
      open,
      pcomAdvancedTargetMode,
      setPcomAdvancedTargetMode,
      pcomAdvancedDeviceIp,
      setPcomAdvancedDeviceIp,
      pcomDevicesLoading,
      pcomDeviceOptions,
      pcomAdvancedManualIp,
      setPcomAdvancedManualIp,
      pcomAdvancedSnmpVersion,
      setPcomAdvancedSnmpVersion,
      pcomAdvancedCommunity,
      setPcomAdvancedCommunity,
      pcomAdvancedOidEnabled,
      setPcomAdvancedOidEnabled,
      pcomAdvancedOidValue,
      setPcomAdvancedOidValue,
      pcomAdvancedSecurityLevel,
      setPcomAdvancedSecurityLevel,
      pcomAdvancedUsername,
      setPcomAdvancedUsername,
      pcomAdvancedAuthProtocol,
      setPcomAdvancedAuthProtocol,
      pcomAdvancedAuthPassword,
      setPcomAdvancedAuthPassword,
      pcomAdvancedPrivProtocol,
      setPcomAdvancedPrivProtocol,
      pcomAdvancedPrivPassword,
      setPcomAdvancedPrivPassword,
      pcomAdvancedEngineId,
      setPcomAdvancedEngineId,
      onClose,
      onApply,
    }),
    [
      open,
      pcomAdvancedTargetMode,
      setPcomAdvancedTargetMode,
      pcomAdvancedDeviceIp,
      setPcomAdvancedDeviceIp,
      pcomDevicesLoading,
      pcomDeviceOptions,
      pcomAdvancedManualIp,
      setPcomAdvancedManualIp,
      pcomAdvancedSnmpVersion,
      setPcomAdvancedSnmpVersion,
      pcomAdvancedCommunity,
      setPcomAdvancedCommunity,
      pcomAdvancedOidEnabled,
      setPcomAdvancedOidEnabled,
      pcomAdvancedOidValue,
      setPcomAdvancedOidValue,
      pcomAdvancedSecurityLevel,
      setPcomAdvancedSecurityLevel,
      pcomAdvancedUsername,
      setPcomAdvancedUsername,
      pcomAdvancedAuthProtocol,
      setPcomAdvancedAuthProtocol,
      pcomAdvancedAuthPassword,
      setPcomAdvancedAuthPassword,
      pcomAdvancedPrivProtocol,
      setPcomAdvancedPrivProtocol,
      pcomAdvancedPrivPassword,
      setPcomAdvancedPrivPassword,
      pcomAdvancedEngineId,
      setPcomAdvancedEngineId,
      onClose,
      onApply,
    ],
  );
}