import { useMemo } from 'react';

type UsePcomWorkspaceViewPropsArgs = any;

export default function usePcomWorkspaceViewProps(args: UsePcomWorkspaceViewPropsArgs) {
  const {
    comBrowserPanelProps,
    selectedFile,
    formatDisplayPath,
    browseNode,
    isFavorite,
    toggleFavorite,
    viewMode,
    setViewMode,
    pcomParsed,
    pcomObjectEntries,
    pcomSelectedObject,
    setPcomSelectedObjectKey,
    formatPcomValue,
    searchHighlightActive,
    highlightQuery,
    rawMatchPositions,
    rawMatchIndex,
    handlePrevRawMatch,
    handleNextRawMatch,
    editorText,
    renderRawHighlightedText,
  } = args;

  return useMemo(
    () => ({
      comBrowserPanelProps,
      selectedFile,
      formatDisplayPath,
      browseNode,
      isFavorite,
      toggleFavorite,
      viewMode,
      setViewMode,
      pcomParsed,
      pcomObjectEntries,
      pcomSelectedObject,
      setPcomSelectedObjectKey,
      formatPcomValue,
      searchHighlightActive,
      highlightQuery,
      rawMatchPositions,
      rawMatchIndex,
      handlePrevRawMatch,
      handleNextRawMatch,
      editorText,
      renderRawHighlightedText,
    }),
    [
      comBrowserPanelProps,
      selectedFile,
      formatDisplayPath,
      browseNode,
      isFavorite,
      toggleFavorite,
      viewMode,
      setViewMode,
      pcomParsed,
      pcomObjectEntries,
      pcomSelectedObject,
      setPcomSelectedObjectKey,
      formatPcomValue,
      searchHighlightActive,
      highlightQuery,
      rawMatchPositions,
      rawMatchIndex,
      handlePrevRawMatch,
      handleNextRawMatch,
      editorText,
      renderRawHighlightedText,
    ],
  );
}