import { useMemo } from 'react';

type UseUserPreferencesModalPropsArgs = any;

export default function useUserPreferencesModalProps(args: UseUserPreferencesModalPropsArgs) {
  const {
    open,
    overviewRebuildPending,
    overviewStatus,
    overviewProgress,
    overviewProgressPercent,
    overviewCacheLabel,
    handleRefreshOverviewCache,
    searchRebuildPending,
    searchStatus,
    searchProgress,
    searchProgressPercent,
    searchCacheLabel,
    handleRefreshSearchCache,
    folderRebuildPending,
    folderOverviewStatus,
    folderProgress,
    folderProgressPercent,
    folderCacheLabel,
    handleRefreshFolderCache,
    mibTranslateCacheLabel,
    refreshMibTranslateStatus,
    cacheActionMessage,
    formatTime,
    onClose,
  } = args;

  return useMemo(
    () => ({
      open,
      overviewRebuildPending,
      overviewStatus,
      overviewProgress,
      overviewProgressPercent,
      overviewCacheLabel,
      handleRefreshOverviewCache,
      searchRebuildPending,
      searchStatus,
      searchProgress,
      searchProgressPercent,
      searchCacheLabel,
      handleRefreshSearchCache,
      folderRebuildPending,
      folderOverviewStatus,
      folderProgress,
      folderProgressPercent,
      folderCacheLabel,
      handleRefreshFolderCache,
      mibTranslateCacheLabel,
      refreshMibTranslateStatus,
      cacheActionMessage,
      formatTime,
      onClose,
    }),
    [
      open,
      overviewRebuildPending,
      overviewStatus,
      overviewProgress,
      overviewProgressPercent,
      overviewCacheLabel,
      handleRefreshOverviewCache,
      searchRebuildPending,
      searchStatus,
      searchProgress,
      searchProgressPercent,
      searchCacheLabel,
      handleRefreshSearchCache,
      folderRebuildPending,
      folderOverviewStatus,
      folderProgress,
      folderProgressPercent,
      folderCacheLabel,
      handleRefreshFolderCache,
      mibTranslateCacheLabel,
      refreshMibTranslateStatus,
      cacheActionMessage,
      formatTime,
      onClose,
    ],
  );
}